### PR TITLE
Refactor - Remove community_server

### PR DESCRIPTION
**Pull request by Elweyn**
## 🍰 Pullrequest
Remove the community_server folder and each references in the gradido folder.

### Issues

- requires #1407

### Todo

- [X] Create new Repository community_server
- [X] Move directory community_server in gradido/gradido to gradido/community_server
- [x] Set tag last-community_server on master

### CODE REVIEW

**Review by Mogge — DISMISSED** [review]
Please push a tag `last-community_server` on master before merging this. Create a copy of the community server on gradido repository

**Comment by Elweyn** [comment]
@Mogge OK so I would make a git tag -a last-community_server & instead of deleting community_server folder create a new Repository did I understand it right?

**Comment by Elweyn** [comment]
Created a repository community_server on the gradido organization!

**Review by Mogge — APPROVED** [review]

**Review by einhornimmond — APPROVED** [review]
seems okay

**Review by ulfgebhardt — APPROVED** [review]

**Pull request merged**
