### PR TITLE
change transaction default order

### LINKED ISSUE #328: 🐛 [Bug] Wrong Order of Transactions
## 🐛 Bugreport

Order of transactions is ascendant. Please descendant as default 

The transaction update method is not called from GddTable.

### PR DESCRIPTION
**Pull request by einhornimmond**
- fixes #328

### CODE REVIEW

**Comment by Mogge** [comment]
I suggest to do this in the with the default request.

**Comment by Mogge** [comment]
I think  this is the better solution: #332

**Review by Mogge — CHANGES_REQUESTED** [review]
See my comments. I suggest to close this approach.

**Comment by ulfgebhardt** [comment]
Both approaches do not exclude each other. Tho we have to think about if this change effects the old frontend.

**Pull request closed without merging**
