### PR TITLE
Docu

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

- included existing docu
- transformed a lot of odt & txt files to md format

### Issues

- relates #165 

### Todo

- [ ] Publish and archive the https://github.com/gradido/gradido_concept repo (and check if everything is there beforehand)

### CODE REVIEW

**Comment by einhornimmond** [comment]
It seems you have mixed up my Ideas and Pauls ideas.
Many ideas from Pauls I don't like and don't think we need them, but I must think about it and take me time for it.
In my Vision the network is simpler as Pauls cluster-structure.

**Comment by ulfgebhardt** [comment]
Will you correct it @einhornimmond ?

**Review by Mogge — APPROVED** [review]

**Comment by einhornimmond** [comment]
Yeah I will correct it, but not now. I think I need several hours for that.

**Comment by ulfgebhardt** [comment]
So should I merge it and you make a new PR or will you work on this PR @einhornimmond ?

**Comment by einhornimmond** [comment]
I will work on it in this PR

**Comment by ulfgebhardt** [comment]
I merge this for now, just open a PR if you want to work on the docu

**Pull request merged**
