### PR TITLE
1594 show transaction was created by link

### LINKED ISSUE #1594: 🚀 [Feature] Frontend: Show if a transaction was created by link
## 🚀 Feature

Show if a transaction was created by link. This could be done via an extra icon like chain-link.

- requires #1556

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
set link icon if transactionLinkId not null 

### Issues
- fixes #1594 

FireShot Capture 1055 -  - localhost

FireShot Capture 1056 -  - localhost

### CODE REVIEW

**Review by ulfgebhardt — CHANGES_REQUESTED** [review]
The implementation is fine, but the layout is not the best.

Consider to place the link symbol on the lower left corner instead of under the send/receive symbol.

And/Or write `Username via Link` and in German: `Username über einen Link`. Consider to use the icon there

image

**Comment by ogerly** [comment]
FireShot Capture 1057 -  - localhost

FireShot Capture 1058 -  - localhost

**Comment by ulfgebhardt** [comment]
Only the Username should be clickable, the link part must not be clickable.

**Comment by ogerly** [comment]
FireShot Capture 1060 -  - localhost

FireShot Capture 1059 -  - localhost

**Review by ulfgebhardt — APPROVED** [review]

**Pull request merged**
