### PR TITLE
in der overview 5 in der liste alle

### LINKED ISSUE #327: 🐛 [Bug] More than 5 Transactions Are Shown In AccountOverview
## 🐛 Bugreport

image

Only five transactions

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
in der "/overview" werden die letzten 5 transaktionen angezeigt .. 
in der "/transactions werden alle transaktionen angezeigt

### Issues
- fixes #327

### CODE REVIEW

**Comment by einhornimmond** [comment]
you could also use the updated call to ask for only 5 transactions from community-server. 
Moritz has updatet it but I don't know in which pr.

**Comment by ulfgebhardt** [comment]
Das ist die Beste Lösung aus meiner Perspektive, bedarf aber der Gesammtanzahl als Rückgabewert des Aufrufs, da unten drunter `View all x Transactions` steht @einhornimmond @ogerly

**Comment by ulfgebhardt** [comment]
@Mogge How do we model the data in the frontend with the paginated query in mind? Should we merge this for now and later refactor? Seems not clean to me with a field behaving diffrerently depending on which page we currently are. Do we solve this Issue together with pagination?

**Comment by Mogge** [comment]
I pushed a solution inside #273. There I pass a property to `GddTable` which indicates the max number of transactions shown. This should also be the way to handle the pagination.

**Pull request closed without merging**
