### PR TITLE
Admin pending creation queries

### PR DESCRIPTION
**Pull request by Elweyn**
### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Review by Mogge — CHANGES_REQUESTED** [review]
```
{ message: "Cannot query field \"countPendingCreations\" on type \"Query\". Did you mean \"getPendingCreations\"?", locations: […], extensions: {…} }
```
and
```
Uncaught (in promise) Error: Network error: Response not successful: Received status code 400
```
AND
```
 message: "Cannot query field \"note\" on type \"PendingCreation\". Did you mean \"date\"?", locations: […], extensions: {…} }
```
Please test this PR on localhost.

**Comment by Mogge** [comment]
On 1st of December I see the months October, November and December. When I select October, I cannot select the amount of GDD to create.

**Comment by ogerly** [comment]
> On 1st of December I see the months October, November and December. When I select October, I cannot select the amount of GDD to create.

If you have a value of 0 and no radio button can be selected, then you have scooped everything for the month.

**Comment by ogerly** [comment]
> ```
> { message: "Cannot query field \"countPendingCreations\" on type \"Query\". Did you mean \"getPendingCreations\"?", locations: […], extensions: {…} }
> ```
> 
> and
> 
> ```
> Uncaught (in promise) Error: Network error: Response not successful: Received status code 400
> ```
> 
> AND
> 
> ```
>  message: "Cannot query field \"note\" on type \"PendingCreation\". Did you mean \"date\"?", locations: […], extensions: {…} }
> ```
> 
> Please test this PR on localhost.

is fixed .. note to memo .. this should run

**Review by Mogge — APPROVED** [review]
Without page reload the pending creations are not updated. We can fix this later. Please merge

**Pull request merged**
