### PR TITLE
workflows_refactor

### LINKED ISSUE #46: 🚀 [Feature] Publish on Dockerhub for community server, login server, node server
## :rocket: Feature

Finish up the publish workflow

Publish on Dockerhub for
- [ ] community server
- [ ] login server
- [ ] node server

### LINKED ISSUE #92: 💥 [DevOps] Publish docker images for login & community server
## 💥 DevOps ticket

Publish docker images for login & community server on dockerhub (github workflow)

Consider to check for some more speedup options when building on github(fresh) and locally(mostly rebuilding - maybe cache the build folder on a volume?)

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

refactor workflows
- adjust names
- publish community_server
- publish login_server
- test build & publish nginx
- test build & publish mariadb

### Issues

- fixes #46 
- fixes #92 

### Todo

- [x] publish workflow only on master after success + enable tagging again

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
@einhornimmond I cannot build the login server production environment. I removed the `iroha-ed25519` build, but it still does not build. Can you fix it (preferable in this PR/branch)?

**Comment by einhornimmond** [comment]
Yeah, I think I can fix it. 
In your publish.yml I find runs-on: ubuntu-latest
but I use the image: conanio/gcc7 as basis for the build. 
Can that work this way?

**Comment by einhornimmond** [comment]
Docker login-server release build is now working but it needs some time. 
Should I create also a config where the dependencies are taken from prebuild docker images like for the debug version?

**Review by einhornimmond — APPROVED** [review]

**Comment by ulfgebhardt** [comment]
Nah its fine as long as stuff builds @einhornimmond 
It would be more important to hook the clicktip thingy

**Pull request merged**
