### PR TITLE
[Invalid] feat(backend): expose federation keypair to backend

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

expose federation keypair to backend so we can use it to encrypt and sign things.

This is done without importing the dht library, but uses the existing sodium-native lib to generate the seed.

### Issues

- releates https://github.com/gradido/gradido/pull/2975 

### Todo

- [X] None

### CODE REVIEW

**Review by Elweyn — APPROVED** [review]
Seems good for me, but @clauspeterhuebner please look also at this!

**Comment by ulfgebhardt** [comment]
> defining the key FEDERATION_DHT_SEED additionally in the backend .env-files will cause conflicts between the dht-node definition and possibly different definition here. As in the requirement of this PR described, it is the goal to offer the generated keypair in all modules, which need them:
> 
> * dht-node-modul to take part of the dht-hyperswarm
> * backend-modul to en/crypt and sign future handshake data
> * federation-modul to en/crypt and sign future handshake data
> * devop requirement to separate these Admin-Configs from Developer/Application-Configs
> 
> The same here as mentioned several times: if we want to work as a team, we have to communicate before spending efforts in dupplicate solutions if you had took a look in the #2955 there exists still an implemented solution about this topic, which i discussed with you and Moritz in our technical architecture meeting two week ago.

I dont understand how you provide the private key to the backend in the linked pr #2955 - i need the private key for the upcomming encryption for authentication -> as descirbed in the PRs description

**Comment by ulfgebhardt** [comment]
This PR is invalid - we will solve this differently. I keep this open till the problem is solved

**Comment by ulfgebhardt** [comment]
Superseded by https://github.com/gradido/gradido/pull/3024

**Pull request closed without merging**
