### PR TITLE
feat(frontend): move the information about gradido being free to the auth layout

### LINKED ISSUE #2343: 🚀 [Feature] Gradido is free - worldwide on startpage slider
## 🚀 Feature

Gradido is free - worldwide on startpage slider

`Gradido ist weltweit kostenfrei.`

There is a key `isFree` in the locales existing showing the sentence on logout:
`Der entsprechende Locale-Key isFree kommt momentan nur in frontend/src/components/LinkInformations/RedeemLoggedOut.vue vor.`

Must be shown on
- [x] logout
- [x] login
- [x] register

### PR DESCRIPTION
**Pull request by mahula**
## 🍰 Pullrequest
The information about Gradido being free worldwide was only displayed in the layout for a redeem link in the logged out context.

This information is now displayed on prominent place - in the auth layout:
- login page
- registration oage
- redeem link context:
  - login
  - registration
  - logged out

2349-free-information-in-auth-layout

### Issues
- fixes #2343

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
Looks good code wise, can I have a screenshot pls?

**Comment by mahula** [comment]
> can I have a screenshot pls?

Sure, see PR description.

**Comment by ulfgebhardt** [comment]
This is codewise cool, design wise I see a problem here - lets have a discussion about this - sorry for that

**Comment by ulfgebhardt** [comment]
```
Hey @Hardy-Hart-am-Start ,
magst du bitte mal auf diesen PR schauen: https://github.com/gradido/gradido/issues/2349
Der Screenshot zeigt die Idee "Gradido ist weltweit kostenlos"  auf allen Start-Seiten (login, register, register via link, ...) anzuzeigen.
Ich hab das blockiert, weil das Design-Technisch aus meiner Laien-Perspektive scheiße aussieht. Das hat im Team auch Zustimmung erfahren und es gab die Ansage dir dir Aufgabe zu übertragen.
Also: Magst du uns sagen wo wir diesen Text am besten platzieren innerhalb deines Designs, wenn wir diesen auf allen Start-Seiten haben wollen?

Neben dem PR gibt es auch noch das dazugehörige Issue: <https://github.com/gradido/gradido/issues/2343>

LG Ulf
```

**Comment by mahula** [comment]
As decided in the design and style channel, the text is at the top of the card on auth pages (sign in and sign up and the reated pages when redeeming a link) now:

Auswahl_011

**Review by ulfgebhardt — APPROVED** [review]

**Pull request merged**
