### PR TITLE
Improve workflows

### LINKED ISSUE #44: 🔧 [Refactor] Workflows
## :zap: Refactor ticket

Refactor Workflow files
- [ ] Remove on-push workflow
- [ ] Integrate gradido node test into test workflow

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

- build community server
- build login server
- removed old gradido node push workflow(not working)

Result can be seen here: https://github.com/gradido/gradido/actions/runs/668728409

### Issues

- fixes #44 

### Todo

- [X] None

### CODE REVIEW

**Review by Mogge — APPROVED** [review]
Cool. How long takes the build for the backend parts?

**Review by einhornimmond — APPROVED** [review]
Seems to be okay. 
Community Server load his config from gradido/configs in build step, login-server at runtime (./configs/login_server:/etc/grd_login)
That's why they different. But we can choose one of this two strategies for both, but which? Which is better?

**Comment by ulfgebhardt** [comment]
Build takes a bit less then 40min @Mogge

**Comment by ulfgebhardt** [comment]
I don't Kind seither strategy @einhornimmond tho I beliwvw it has no effect on the build time

**Pull request merged**
