### PR TITLE
Fix compose bug

### PR DESCRIPTION
**Pull request by einhornimmond**
## 🍰 Pullrequest
in frontend 
depends_on:
  - nginx
  
leads to circular dependencie because nginx depens_on frontent. 
Removed it.

By the way add debug message to Login-Server after he starts visible also in docker. 

Make VUE_PATH default to /vue and copy back vue changes in nginx.conf so that on default composer-build
the new client is reachable with http://localhost/vue

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
I do not understand why nginx depends on frontend. Same applies for the login server. Nginx is the webserver and should run when we register the services. If its working I will not object, but I believe the configuration is off regarding logic and standards.

**Comment by ulfgebhardt** [comment]
Does this solve #131 ?

**Review by ulfgebhardt — APPROVED** [review]

**Comment by ulfgebhardt** [comment]
We seem to need this to have the master composing again - therefore I consider to merge it and maybe make a followup issue

**Comment by einhornimmond** [comment]
In nginx config I use 
- proxy_pass          http://login-server:1200;
- proxy_pass          http://login-server:1201;
- proxy_pass          http://frontend:8080;
- fastcgi_pass         community-server:9000;

It seems that before starting nginx check if the services are reachable and if not, don't start. 
At least that was what I experienced as I startet with nginx. 
So it is important that this services running before nginx can start. 
If you find a another way, do it.

**Pull request merged**
